In [109]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

%matplotlib inline
import sys
import six
import numpy as np

## 1-1-1

In [110]:
output = 'Hello Python'
print(output)

Hello Python


## 1-1-2

In [111]:
print('len of word = {}'.format(len(output)))

len of word = 12


## 1-1-3

In [112]:
# python file(*.py)で実行した時のコードを載せる
param = sys.argv
arg_in = param[1]
print(arg_in)
print('len of input word = {}'.format(len(arg_in)))

-f
len of input word = 2


## 1-1-4

In [113]:
n_r = 5
r_list = np.random.uniform(0., 1., n_r)
print(r_list)

for i in range(n_r-1, 0, -1):
    for j in range(0, i):
        if r_list[j] > r_list[j + 1]:
            temp = r_list[j + 1]
            r_list[j + 1] = r_list[j]
            r_list[j] = temp
print(r_list)

[ 0.51738693  0.25514257  0.47380029  0.35394569  0.29957938]
[ 0.25514257  0.29957938  0.35394569  0.47380029  0.51738693]


## 1-1-5

In [133]:
n_list = []
for i in six.moves.range(1, 101):
    n_list.append(i)
print(n_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


## 1-1-6

In [134]:
n_nlist = [i for i in six.moves.range(1, 101)]
print(n_nlist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


## 1-1-7

In [135]:
for i in six.moves.range(len(n_list)):
    print(n_list[i], end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

## 1-1-8

In [136]:
for i in n_list:
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

## 1-1-9

In [137]:
for i in n_list:
    if i %15 == 0:
        print('fizzbuzz', end=" ")
    elif i % 3 == 0:
        print('fizz', end=" ")
    elif i % 5 == 0:
        print('buzz', end=" ")
    else:
        print(i, end=" ")

1 2 fizz 4 buzz fizz 7 8 fizz buzz 11 fizz 13 14 fizzbuzz 16 17 fizz 19 buzz fizz 22 23 fizz buzz 26 fizz 28 29 fizzbuzz 31 32 fizz 34 buzz fizz 37 38 fizz buzz 41 fizz 43 44 fizzbuzz 46 47 fizz 49 buzz fizz 52 53 fizz buzz 56 fizz 58 59 fizzbuzz 61 62 fizz 64 buzz fizz 67 68 fizz buzz 71 fizz 73 74 fizzbuzz 76 77 fizz 79 buzz fizz 82 83 fizz buzz 86 fizz 88 89 fizzbuzz 91 92 fizz 94 buzz fizz 97 98 fizz buzz 

## 1-1-10

In [138]:
for i in n_list:
    (print("fizzbuzz", end="")) if (i % 15 == 0)\
    else ((print("fizz", end="")) if (i % 3 == 0)\
          else ((print("buzz", end="")) if (i % 5 == 0) else(print(i, end=""))))

12fizz4buzzfizz78fizzbuzz11fizz1314fizzbuzz1617fizz19buzzfizz2223fizzbuzz26fizz2829fizzbuzz3132fizz34buzzfizz3738fizzbuzz41fizz4344fizzbuzz4647fizz49buzzfizz5253fizzbuzz56fizz5859fizzbuzz6162fizz64buzzfizz6768fizzbuzz71fizz7374fizzbuzz7677fizz79buzzfizz8283fizzbuzz86fizz8889fizzbuzz9192fizz94buzzfizz9798fizzbuzz

## 1-1-11

In [139]:
fb_list = [("fizzbuzz") if (i % 15 == 0) else ("fizz") if (i % 3 == 0)\
           else ("buzz") if (i % 5 == 0) else(i) for i in six.moves.range(1, 101)]
print(fb_list)
print("ダブりのない要素数＝", len(list(set(fb_list))))

[1, 2, 'fizz', 4, 'buzz', 'fizz', 7, 8, 'fizz', 'buzz', 11, 'fizz', 13, 14, 'fizzbuzz', 16, 17, 'fizz', 19, 'buzz', 'fizz', 22, 23, 'fizz', 'buzz', 26, 'fizz', 28, 29, 'fizzbuzz', 31, 32, 'fizz', 34, 'buzz', 'fizz', 37, 38, 'fizz', 'buzz', 41, 'fizz', 43, 44, 'fizzbuzz', 46, 47, 'fizz', 49, 'buzz', 'fizz', 52, 53, 'fizz', 'buzz', 56, 'fizz', 58, 59, 'fizzbuzz', 61, 62, 'fizz', 64, 'buzz', 'fizz', 67, 68, 'fizz', 'buzz', 71, 'fizz', 73, 74, 'fizzbuzz', 76, 77, 'fizz', 79, 'buzz', 'fizz', 82, 83, 'fizz', 'buzz', 86, 'fizz', 88, 89, 'fizzbuzz', 91, 92, 'fizz', 94, 'buzz', 'fizz', 97, 98, 'fizz', 'buzz']
ダブりのない要素数＝ 56


## 1-1-12

In [140]:
n_fr = 50
f_list = fb_list[:n_fr]
r_list = fb_list[n_fr: ]
print('前半リストの要素数={}, 後半のリストの要素数={}'.format(len(f_list), len(r_list)))

# debug
print(f_list)
print(r_list)

前半リストの要素数=50, 後半のリストの要素数=50
[1, 2, 'fizz', 4, 'buzz', 'fizz', 7, 8, 'fizz', 'buzz', 11, 'fizz', 13, 14, 'fizzbuzz', 16, 17, 'fizz', 19, 'buzz', 'fizz', 22, 23, 'fizz', 'buzz', 26, 'fizz', 28, 29, 'fizzbuzz', 31, 32, 'fizz', 34, 'buzz', 'fizz', 37, 38, 'fizz', 'buzz', 41, 'fizz', 43, 44, 'fizzbuzz', 46, 47, 'fizz', 49, 'buzz']
['fizz', 52, 53, 'fizz', 'buzz', 56, 'fizz', 58, 59, 'fizzbuzz', 61, 62, 'fizz', 64, 'buzz', 'fizz', 67, 68, 'fizz', 'buzz', 71, 'fizz', 73, 74, 'fizzbuzz', 76, 77, 'fizz', 79, 'buzz', 'fizz', 82, 83, 'fizz', 'buzz', 86, 'fizz', 88, 89, 'fizzbuzz', 91, 92, 'fizz', 94, 'buzz', 'fizz', 97, 98, 'fizz', 'buzz']


## 1-1-13

In [141]:
fix_list = []
fix_list.extend(f_list)
fix_list.extend(r_list)
print("連結したリストfix_listの要素数＝", len(fix_list))

#debug
print(fix_list)

連結したリストfix_listの要素数＝ 100
[1, 2, 'fizz', 4, 'buzz', 'fizz', 7, 8, 'fizz', 'buzz', 11, 'fizz', 13, 14, 'fizzbuzz', 16, 17, 'fizz', 19, 'buzz', 'fizz', 22, 23, 'fizz', 'buzz', 26, 'fizz', 28, 29, 'fizzbuzz', 31, 32, 'fizz', 34, 'buzz', 'fizz', 37, 38, 'fizz', 'buzz', 41, 'fizz', 43, 44, 'fizzbuzz', 46, 47, 'fizz', 49, 'buzz', 'fizz', 52, 53, 'fizz', 'buzz', 56, 'fizz', 58, 59, 'fizzbuzz', 61, 62, 'fizz', 64, 'buzz', 'fizz', 67, 68, 'fizz', 'buzz', 71, 'fizz', 73, 74, 'fizzbuzz', 76, 77, 'fizz', 79, 'buzz', 'fizz', 82, 83, 'fizz', 'buzz', 86, 'fizz', 88, 89, 'fizzbuzz', 91, 92, 'fizz', 94, 'buzz', 'fizz', 97, 98, 'fizz', 'buzz']


## 1-1-14

In [142]:
def calc(a, b):
    c = a + b
    d = a - b
    
    return (c, d)


print ("返値＝", calc(3, 2)[0])

# tips
c, d = calc(3, 2)
print("返値=", d)

返値＝ 5
返値= 1


## 1-1-15

In [143]:
imabari = {'ehime':'no', 'mikan':'ha', 'ni':'ho', 'n':'No.1!!!'}

for k in imabari.keys():
    print(k, imabari[k])

#.keys()で呼ばれるkeyの順番はソートされる？？

ehime no
ni ho
mikan ha
n No.1!!!


## 1-1-16

In [144]:
alp_dic = {}
alp = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',\
       'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

for k, d in enumerate(alp):
    alp_dic[k] = d

for k in six.moves.range(26):
    print("key={}, data={}".format(k, alp_dic[k]), end=" ")

key=0, data=A key=1, data=B key=2, data=C key=3, data=D key=4, data=E key=5, data=F key=6, data=G key=7, data=H key=8, data=I key=9, data=J key=10, data=K key=11, data=L key=12, data=M key=13, data=N key=14, data=O key=15, data=P key=16, data=Q key=17, data=R key=18, data=S key=19, data=T key=20, data=U key=21, data=V key=22, data=W key=23, data=X key=24, data=Y key=25, data=Z 

## 1-1-17

In [145]:
n_max = 10
n_list = [i for i in six.moves.range(10)]
nr_list = [[i, j] for (i, j) in zip(n_list, reversed(n_list))]

print(nr_list)

[[0, 9], [1, 8], [2, 7], [3, 6], [4, 5], [5, 4], [6, 3], [7, 2], [8, 1], [9, 0]]


## 1-1-18

In [146]:
count = 0
for v in [nr_list[i][j] for i in six.moves.range(len(nr_list))\
          for j in six.moves.range(len(nr_list[0]))]:
    if v < 4:
        count +=1
        
print(alp[:count])

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']


## 1-1-19

In [147]:
def hoge_func(a, b):
    return (("iyatomi", "hitoshi"))\
if (a > b[0]) else((('ogawa', 'koichi')) if (a > b[1])\
                   else(('a is smaller than', 'both of b[0] and b[1]')) )

print(hoge_func(a=10, b=(2, 20)))

('iyatomi', 'hitoshi')


## 1-1-20

In [148]:
r_list = [1, 2, 3, 4, 5]
np_list = np.asarray(r_list)
print(np_list)

[1 2 3 4 5]
